#docker-compose.yml
version: "3.8"

services:
    php:
        build: ./docker/php
        volumes:
            - ./app:/var/www/html
        networks:
            - symfony

    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony

networks:
    symfony:
    